name: 'Upload Theme'
description: 'Upload theme to your site'
inputs:
  api-url:
    description: 'API Url'
    required: true
  api-key:
    description: 'API Key'
    required: true
  zip-path:
    description: 'Path to Zip'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'