name: 'Upload Theme'
description: 'Upload theme to your site'
inputs:
  zip-path:
    description: 'Path to Zip'
    required: true
    default: 'theme.zip'
  api-url:
    description: 'API Url'
    required: true
  api-key:
    description: 'API Key'
    required: true
runs:
  using: 'node10'
  main: 'dist/index.js'