name: Deploy theme

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: 'Upload Theme'
        uses: ./.github/actions/upload-theme
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          zip-path: ${{steps.zip.outputs.result}}
