name: Deploy theme

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: 'Upload Theme'
        uses: ./.github/actions/upload-theme
        with:
          api-url: "https://hannah.ghost.io"
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: '*gscan.yml '
