name: Deploy theme

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Create Zip
        run: |
        THEME_NAME=$(jq -r '.name' package.json)
        echo $THEME_NAME
        zip -r $THEME_NAME.zip . -x '*node_modules*' '*.git*' '*\.zip' routes.yaml redirects.yaml redirects.json