name: Staging Deploy Theme
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: Run gscan
        run: |
          npm i -g gscan@latest
          gscan --fatal --verbose $GITHUB_WORKSPACE
      - uses: ./.github/actions/test
        with:
          api-url: ${{ secrets.STG_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.STG_GHOST_ADMIN_API_KEY }}
          theme-name: "my-casper"
