name: Staging Deploy Theme
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run gscan
        run: |
          npm i -g gscan@latest
          gscan -f $GITHUB_WORKSPACE
      - uses: ./.github/actions/test
        with:
          api-url: ${{ secrets.STG_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.STG_GHOST_ADMIN_API_KEY }}
          theme-name: "my-casper"
