name: Update Early Access Posts
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Update Ghost Posts
        uses: TryGhost/action-update-posts@v0.0.2
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          tag: 'hash-sponsored'
          field: 'featured'
          value: false
          days: 7
